name: livesutra
description: "A BIGO Style Live Streaming App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10

  # State Management
  provider: ^6.1.5

  # Live Streaming
  zego_express_engine: ^3.24.1

  # Network
  http: ^1.2.1

  # Images
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0

  # Permissions
  permission_handler: ^12.0.1

  # Local Storage
  shared_preferences: ^2.5.3

  # Notifications
  flutter_local_notifications: ^19.4.0

  # Date & Time
  intl: ^0.20.2

  # Loading
  flutter_easyloading: ^3.0.5

  # Animation
  lottie: ^3.3.2

  # UUID
  uuid: ^4.5.1

  # Audio
  audioplayers: ^6.5.1

  # Chat Auto Scroll
  scrollable_positioned_list: ^0.3.8

  # Environment Variables
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LiveSutra_logo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/LiveSutra_logo.png
  android: true
  ios: true
  
  android_12:
    image: assets/images/LiveSutra_logo.png
    color: "#000000"