// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxMr_uouODUsY2mTMrS24HgjIniBUqoNQ',
    appId: '1:364110402575:web:221f73f6e5fa7fd5fc7f7a',
    messagingSenderId: '364110402575',
    projectId: 'livesutra-2ac28',
    authDomain: 'livesutra-2ac28.firebaseapp.com',
    storageBucket: 'livesutra-2ac28.firebasestorage.app',
    measurementId: 'G-ERMTWHVB5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFz3JNqhEiSqgy9edRcEzSzAMyraWVtIQ',
    appId: '1:364110402575:android:b2020bdb5337360afc7f7a',
    messagingSenderId: '364110402575',
    projectId: 'livesutra-2ac28',
    storageBucket: 'livesutra-2ac28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANEbF8EbgWVQDKB4cjaZJZDn0gaTessI0',
    appId: '1:364110402575:ios:90c2baf5fe64d73dfc7f7a',
    messagingSenderId: '364110402575',
    projectId: 'livesutra-2ac28',
    storageBucket: 'livesutra-2ac28.firebasestorage.app',
    iosBundleId: 'com.example.livesutra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANEbF8EbgWVQDKB4cjaZJZDn0gaTessI0',
    appId: '1:364110402575:ios:90c2baf5fe64d73dfc7f7a',
    messagingSenderId: '364110402575',
    projectId: 'livesutra-2ac28',
    storageBucket: 'livesutra-2ac28.firebasestorage.app',
    iosBundleId: 'com.example.livesutra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxMr_uouODUsY2mTMrS24HgjIniBUqoNQ',
    appId: '1:364110402575:web:8e4c5907e991031efc7f7a',
    messagingSenderId: '364110402575',
    projectId: 'livesutra-2ac28',
    authDomain: 'livesutra-2ac28.firebaseapp.com',
    storageBucket: 'livesutra-2ac28.firebasestorage.app',
    measurementId: 'G-E7H02Q7LKY',
  );
}
